name: 03 - Workflow Runners
on:
  push

jobs:
    ubuntu-echo:
        runs-on: ubuntu-latest
        steps:
            - name: Show the runner
              run: |
                echo "This job is running on an Ubuntu runner!"
                echo "Runner OS: ${{ runner.os }}"
                echo "Runner Name: ${{ runner.name }}"
                echo "Runner Temp Directory: ${{ runner.temp }}"
                echo "Runner Workspace Directory: ${{ runner.workspace }}"
                echo "Runner Architecture: ${{ runner.arch }}"
                echo "Runner Version: ${{ runner.version }}"
    windows-echo:
        runs-on: windows-latest
        steps:
            - name: Show the runner - Windows
              run: |
                echo "This job is running on a Windows runner!"
                echo "Runner OS: ${{ runner.os }}"
                echo "Runner Name: ${{ runner.name }}"
                echo "Runner Temp Directory: ${{ runner.temp }}"
                echo "Runner Workspace Directory: ${{ runner.workspace }}"
                echo "Runner Architecture: ${{ runner.arch }}"
                echo "Runner Version: ${{ runner.version }}"
                